# prettier-ignore
name: Test
on:
  push:
    branches: main

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts

      - name: Install NPM Dependencies
        run: npm i --production=false

      - name: Running Instance
        run: npm run dev
        env: 
          NODE_ENV: development
          DB_URL: ${{ secrets.DB_URL }}

      - name: Testing
        run: npm run test
        env:
          NODE_ENV: development
          DB_URL: ${{ secrets.DB_URL }}
